export const LOGGED_IN = 'LOGGED_IN';
export const LOGGING_IN = 'LOGGING_IN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const SIGNING_UP = 'SIGNING_UP';
export const SIGNED_UP = 'SIGNED_UP';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

// User profile actions
export const UPDATING = 'UPDATING';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FAILED = "UPDATE_FAILED";
export const CLEAN_UP = 'CLEAN_UP';

export const FETCHING_PROFILE = 'FETCHING_PROFILE';
export const FETCHING_PROFILE_SUCCESS = 'FETCHING_PROFILE_SUCCESS';
export const FETCHING_PROFILE_FAILED = 'FETCHING_PROFILE_FAILED';

// Loan application
export const APPLYING_FOR_LOAN = "APPLYING_FOR_LOAN";
export const APPLYING_FOR_LOAN_SUCCESS = "APPLYING_FOR_LOAN_SUCCESS";
export const APPLYING_FOR_LOAN_FAILED = "APPLYING_FOR_LOAN_FAILED";